name: .NET
on:
  workflow_dispatch:
permissions: write-all
jobs:
  build:
    runs-on: windows-latest
    
    steps:
    
    - name: Checkout
      uses: actions/checkout@v4

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: 15.0.28307.329
        msbuild-architecture: x64
          
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v2.0.0
     
    - name: Restore NuGet Packages
      run: nuget restore SnippetManager.sln
 
    - name: Build and Publish App
      run: msbuild SnippetManager.sln /p:Configuration=Release
 
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        name: snippet_manager
        # A file, directory or wildcard pattern that describes what to upload
        path: SnippetManager/bin/Release/*
