name: .NET
on:
    workflow_dispatch:
permissions: write-all
env:
  CODESIGN_PWD: ${{secrets.CODESIGN_PWD}}
  CODESIGN_BASE64: ${{secrets.CODESIGN_B64}}
  GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
jobs:
  build:
    runs-on: windows-2019

    steps:
    
    - name: Checkout
      uses: actions/checkout@v4

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: 15.0.28307.329
        msbuild-architecture: x64
          
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v2.0.0
     
    - name: Restore NuGet Packages
      run: nuget restore SnippetManager.sln
 
    - name: Build and Publish App
      run: msbuild SnippetManager.sln /p:Configuration=Release
    
    - name: Sign executable
      run: |
          $cr = New-Item -ItemType directory -Path cr
          Write-Host "New folder created at $cr"
          $filename = 'cr/cr.pfx'
          $bytes = [Convert]::FromBase64String($env:CODESIGN_BASE64)
          [IO.File]::WriteAllBytes($filename, $bytes)
          Write-Host "$filename successfully created."
          $bins = Get-ChildItem ./SnippetManager/bin/Release/* -Include "*exe","*dll" -Recurse
          foreach ($bin in $bins){
              & 'C:/Program Files (x86)/Windows Kits/10/bin/10.0.22621.0/x86/signtool.exe' sign /fd SHA256 /d "Snippet Manager" /n "Abbasoft" /p $env:CODESIGN_PWD  /f $filename /tr "http://timestamp.sectigo.com/rfc3161" /td sha256 $bin
          }
          Remove-Item -Recurse -Force cr
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        name: snippet_manager
        path: SnippetManager/bin/Release/*
        
    - name: Create Release
      run: |
        gh release create v1.0.0 ./snippet_manager.zip
      env:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
      
